### ISSUE TITLE
Ta hensyn til fravær (ferie o.l.)

### ISSUE THREAD

**Issue by linemos** [navikt/standbot#6]
Mulighet for å legge inn at man har ferie eller lignende og ikke deltar i den perioden.

**Comment by Kyrremann** [comment]
Kan fikse det senere i dag. Tenker det kan løses med `ferie <til dato>`.

**Comment by linemos** [comment]
Ja, det burde holde. Og kanskje med mulighet til å skru på deltagelse tidligere, type `tilbake-fra-ferie` 🤷‍♀️

**Comment by Kyrremann** [comment]
Dette er nå løst med følgende:

`ferie <til-og-med-dato>` - registrere at du har ferie fra og med i dag, til og med en dato
`ferie <fra-og-med-dato>-<til-og-med-dato>` - registrerer perioden du er på ferie
`ferie ferdig` - hvis du er tilbake før den opprinnelige datoen
