### ISSUE TITLE
Offentlig tilgjengelig instans

### ISSUE THREAD

**Issue by evenh** [navikt/standbot#8]
Hei! Jeg la merke til at deres interne instans er eksponert over internett, uten autentisering (webappen). Skal den være offentlig tilgjengelig, eller er det en sikkerhetsglipp? :-)

**Comment by Kyrremann** [comment]
Hei. Det stemmer at den er offentlig tilgjengelig, er ikke en sikkerhetsglipp, men ikke et fremtidig mål at den skal være så åpen. Vi har en sak på å skallsikre den med innlogging. Har bare foreløpig ikke blitt prioritert.

Derfor har vi også informert og oppfordret alle som bruker appen om at den ligger åpent (så får vi bare håpe på at de husker det også).
